### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by S1lenc3-chenmo** [nblog/DeAliWangWang#1]
大佬，我想问一下，这个算法是静态分析得到的吗，我尝试调试，发现存在反调试，而且AliAuthSDK.dll加了VMP，想学习一下思路以及技术。

**Comment by nblog** [comment]
x64dbg分析的，vmp反调试用sharpod就可以了，至少我分析的这部分没有VM混淆，就我写的这部分，并没有多复杂，如果你用IDA F5大法可能更简单。

**Comment by S1lenc3-chenmo** [comment]
感谢大佬解答
